### PR TITLE
Add label support

### PR DESCRIPTION
**Pull request by HexRabbit**
Create a label by using "WORD:", and use ":WORD" to call/jump to that label.
Also modified all test/*.s to match right answer.

### CODE REVIEW

**Comment by jserv** [comment]
Rebasing is required.

**Comment by HexRabbit** [comment]
I've fixed code conflicts, do I still need to do rebase?

**Comment by jserv** [comment]
Rebasing can get rid of "Merge branch 'master' into master".

**Comment by HexRabbit** [comment]
OK. I will open a new pull request.

**Pull request closed without merging**
